# Workflow file adapted from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build and Publish

# Trigger this CD on push
on:
  push:
    # Build on push
    branches:
      - main
      - tmpss
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # Allows running this workflow manually from the Actions tab, useful for Developers who may want
  # to view test status on the production end, prior to main branch merge.
  workflow_dispatch:

env:
  IS_TAGGED_BUILD: ${{ startsWith(github.ref, 'refs/tags/')" }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version

      - name: Restore Packages
        run: dotnet restore

      - name: Build and Publish Tagged Artifact
        if: ${{ env.IS_TAGGED_BUILD }}
        run: dotnet publish --configuration Release --no-restore --runtime win-x64 SimpCity

      - name: Build and Publish Dev Artifact
        if: ${{ !env.IS_TAGGED_BUILD }}
        run: dotnet publish --configuration Release --no-restore --runtime win-x64 -p:DEV_BUILD_ID=${{ github.sha }} SimpCity

      - name: Rename Output
        working-directory: SimpCity\bin\Release\net5.0\win-x64\publish
        run: mv SimpCity.exe SimpCity-win-x64.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimpCity-Artifact
          path: SimpCity\bin\Release
